version: "3.8"

services:
  atlas:
    image: sburn/apache-atlas:latest
    container_name: apache-atlas
    ports:
      - "21000:21000"
    environment:
      - ATLAS_HOME=/opt/atlas
    restart: unless-stopped
